DROP TABLE IF EXISTS test.STUDENT;

CREATE TABLE test.STUDENT (
  FIRST_NAME      VARCHAR(255) ,
  LAST_NAME      VARCHAR(255) ,
  EMAIL      VARCHAR(255) ,
  AGE        VARCHAR(255),
  DEPT_CODE VARCHAR(255)
);

DROP TABLE IF EXISTS test.DEPT;

CREATE TABLE test.DEPT (
  DEPT_CODE      VARCHAR(255) ,
  DEPT_NAME      VARCHAR(255) 
);

INSERT INTO test.DEPT(DEPT_CODE,DEPT_NAME) VALUES ('100','SCIENCE');
INSERT INTO test.DEPT(DEPT_CODE,DEPT_NAME) VALUES ('200','COMMERCE');
INSERT INTO test.DEPT(DEPT_CODE,DEPT_NAME) VALUES ('300','ARTS');
INSERT INTO test.DEPT(DEPT_CODE,DEPT_NAME) VALUES ('400','MATHS');


DROP TABLE IF EXISTS test.STUD_DEPT;

CREATE TABLE test.STUD_DEPT (
  FIRST_NAME     VARCHAR(255) ,
  DEPT_NAME      VARCHAR(255)
);



